"""Codebook for the Sanmli TH-05 LED candle set.

Generated by WigFactory from `sanmli-candles-th05.wig.json`, which carries a
complete signed fitting. Every value below was decoded from a captured signal
by HAIR's RC-5 decoder and verified in both directions before publication. No
code here was inferred, extrapolated or filled in by hand.

RC-5 carries a toggle bit that flips on every key press so a receiver can tell
a held key from two presses. It is press state and not identity, so it is not
part of the codebook; the integration keeps one toggle per config entry and
advances it after each send.
"""

from __future__ import annotations

from enum import IntEnum

from .decoder import RC5Command

PROTOCOL = "RC5"

# The RC-5 system address shared by every signal in the wig. Also a soft
# signal for sibling products: a rebadged unit from the same maker usually
# keeps the address whatever the logo on the shell says.
ADDRESS = 0x1F


class SanmliTh05Code(IntEnum):
    """RC-5 command values for the Sanmli TH-05 candle remote."""

    ON = 0x01
    OFF = 0x08
    FLICKER = 0x02
    FADE_OUT = 0x06
    CANDLE_LIKE = 0x0C
    SOLID_LIGHT = 0x0E
    BRIGHTEN = 0x0B
    DIM = 0x0A
    TIMER_2H = 0x10
    TIMER_4H = 0x04
    TIMER_6H = 0x20
    TIMER_8H = 0x12

    def to_command(
        self, *, toggle: int = 0, repeat_count: int = 0
    ) -> RC5Command:
        """Build the RC-5 command for this code."""
        return RC5Command(
            address=ADDRESS,
            command=int(self),
            toggle=toggle & 1,
            repeat_count=repeat_count,
        )


# The provenance record, and what makes this codebook machine checkable.
#
# Keys are the wig's aliases verbatim, including their spacing and their
# parenthetical notes, because that is what the person who fitted this device
# actually labelled each button. WigFactory's gate walks this mapping in both
# directions: every alias must have exactly one code, and every code must trace
# back to exactly one alias. Do not tidy the keys.
WIG_ALIASES: dict[str, SanmliTh05Code] = {
    "On": SanmliTh05Code.ON,
    "Off": SanmliTh05Code.OFF,
    "SL (Candle Like)": SanmliTh05Code.CANDLE_LIKE,
    "Light (Solid Light)": SanmliTh05Code.SOLID_LIGHT,
    "8 Hour": SanmliTh05Code.TIMER_8H,
    "6 Hour": SanmliTh05Code.TIMER_6H,
    "4 Hour": SanmliTh05Code.TIMER_4H,
    "Brighten Up": SanmliTh05Code.BRIGHTEN,
    "Dim Down": SanmliTh05Code.DIM,
    "BL (Fade Out)": SanmliTh05Code.FADE_OUT,
    "2 Hour": SanmliTh05Code.TIMER_2H,
    "FL (Flicker)": SanmliTh05Code.FLICKER,
}
